apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
#  fsType: xfs
  cephfs:
    monitors:
    - 192.168.1.230:6789
    - 192.168.1.236:6789
    - 192.168.1.231:6789
    path: /test
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
