---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins2
  namespace: test
spec:
  template:
    metadata:
      labels:
        app: jenkins2
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: jenkins2
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        - containerPort: 50000
          name: agent
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
    #    livenessProbe:
    #      httpGet:
    #        path: /login
    #        port: 8080
    #      initialDelaySeconds: 1500
    #      timeoutSeconds: 500
    #      failureThreshold: 12
    #    readinessProbe:
    #      httpGet:
    #        path: /login
    #        port: 8080
    #      initialDelaySeconds: 1500
    #      timeoutSeconds: 500
    #      failureThreshold: 12
        volumeMounts:
        - name: jenkinshome
          subPath: jenkins2
          mountPath: /var/jenkins_home
      securityContext:
        fsGroup: 1000
      volumes:
      - name: jenkinshome
        persistentVolumeClaim:
          claimName: jenkinsfs

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins2
  namespace: test
  labels:
    app: jenkins2
spec:
  selector:
    app: jenkins2
  type: NodePort
  ports:
  - name: web
    port: 8080
    targetPort: web
    nodePort: 30005
  - name: agent
    port: 50000
    targetPort: agent
