kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dynamic-cephfs
  namespace: test
provisioner: ceph.com/cephfs
parameters:
    monitors: 192.168.1.230:6789,192.168.1.231:6789,192.168.1.236:6789
    adminId: admin
    adminSecretName: ceph-secret
    adminSecretNamespace: "test"
    claimRoot: /test
