---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab
  namespace: kube-ops

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gitlab
  namespace: kube-ops
subjects:
  - kind: ServiceAccount
    name: gitlab
    namespace: kube-ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
